app/projects/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectMultipleField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from flask_babel import lazy_gettext
from ..models import Project
from wtforms.widgets import TextArea, CheckboxInput, ListWidget





class ProjectForm(Form):
    name = StringField('Project Name', validators=[Required(), Length(1, 256), 
                    Regexp('^[A-Za-z][A-Za-z0-9_]*$', 0,
                           'Project name must have only letters (A-Z, a-z), '
                           'numbers or underscores')], 
                           render_kw={"placeholder": "Project name must have only letters (A-Z, a-z, _)"})
    url = StringField('Sites', validators=[Required(), Length(1, 1000)], 
                            render_kw={"placeholder": "site.com, site.de, site.net"})
    requirements = StringField('Requirements', validators=[Required(), Length(1, 2000)], widget=TextArea(), 
                               render_kw={"placeholder": "Detailed description of the data required from the site."})
    
    download_filetype = SelectMultipleField('Download file type <small>(Use Ctrl to select multiple)</small>', 
                            choices=[('CSV','CSV format'),
                                     ('Sqlite','Sqlite format'), 
                                     ('Text','Text format')], default = ('CSV','CSV format'))
                            #option_widget=CheckboxInput(), widget = ListWidget(html_tag='ul', prefix_label=False))
    Submit = SubmitField('Create Project')
    
    
    

    
class ProjectButton(Form):
    download = SubmitField(lazy_gettext('Download'))
    update = SubmitField(lazy_gettext('Update'))
    delete = SubmitField(lazy_gettext('Delete'))

app/projects/__init__.py
from flask import Blueprint

projects = Blueprint('projects', __name__)

from . import views

app/projects/views.py
from flask import render_template, redirect, request, url_for, \
                flash, send_from_directory
from flask_login import login_user, logout_user, login_required, current_user
from flask_babel import gettext as _
import os
from pathlib import Path

from . import projects
from .. import db
from ..models import Project, User
from ..email import send_email
from .forms import ProjectForm, ProjectButton
from config import basedir


'''
@projects.route('/')
def index():
    return render_template('projects/index.html')
'''

@projects.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    form = ProjectForm()
    projects = db.session.query(Project).filter_by(author_id=current_user.id).order_by(db.desc(Project.updated_on)).all()
    if form.validate_on_submit():
        if projects is not None:
            '''Check only projects from the same user that are not deleted.'''
            project_name = [project_name.name for project_name in projects]
            deleted_project = []
            for project in projects:
                if project.deleted is False:
                    deleted_project.append(project.name)
            if form.name.data in project_name and deleted_project:
                flash('Please choose a new name. It already exists.')
            else:
                url = form.url.data # no sanitize # sanitize url to add http://
                name = form.name.data
                new_project=Project(name=name, url=url,
                    requirements=form.requirements.data, author_id=current_user.id, download_filetype=form.download_filetype.data)
                db.session.add(new_project)
                db.session.commit()
                #latest_project = db.session.query(Project).filter_by(name=name).order_by(db.desc(Project.created_on)).first()
                #scrap_template(name, url, latest_project.id, latest_project.download_filetype) # create template for the project
                scrap_template(name)
                flash('Your new Project has been added. You shall receive an email as' \
                    ' soon as we are done with the configuration.')
            return redirect(url_for('.dashboard'))
    return render_template('projects/dashboard.html', projects=projects, form=form)


def sanitize_url(url):
    if 'http://' or 'https://' in url[0:8]:
        url = url
    else:
        url = 'http://' + url
    return url

def scrap_template(name):
    latest_project = db.session.query(Project).filter_by(name=name).first()
    dir_name = os.path.join(basedir, 'static', "ScrapProjects/{}/".format(latest_project.id))
    os.makedirs(os.path.join(dir_name, name), exist_ok=True) # directory for the codes
    if 'CSV' in latest_project.download_filetype:
        os.makedirs(os.path.join(dir_name, 'csv'), exist_ok=True) # directory for csv files
    if 'Sqlite' in latest_project.download_filetype:
        os.makedirs(os.path.join(dir_name, 'sqlite'), exist_ok=True) # directory for sqlite files    
    if 'Text' in latest_project.download_filetype:
        os.makedirs(os.path.join(dir_name, 'text'), exist_ok=True) # directory for text files
        
    
    
    
@projects.route("/delete", methods=['POST'])
@login_required
def delete():
    if request is not None:
        project_id = int(request.form['project_to_delete_id'])
        project = db.session.query(Project).filter_by(id=project_id).first()
        if 'delete' in request.form: 
            #project = db.session.query(Project).filter_by(id=project_id).first()
            #name = project.name
            #db.session.delete(project)
            #db.session.commit()
            project.deleted = True
            flash(_('%s has been permanently deleted.' % project.name))
        elif 'update' in request.form: 
            flash('Update pressed. Project id is {}'.format(project_id))
    return redirect(url_for('.dashboard'))


'''
@projects.route("/download", method=['GET'])
@login_required
def download():
    flash(('id : {}, user : {}, filetype : {}').format(request.args.get('id'), request.args.get('user'), request.args.get('filetype')))

'''

@projects.route('/download/<int:project_id>/<filetype>')
@login_required
def download(project_id, filetype):
    project = db.session.query(Project).filter_by(id=project_id).first()
    filetype = filetype.lower()
    if project.author_id == current_user.id:
        dir = os.path.join(basedir, 'static', "ScrapProjects/{}/".format(project_id), filetype)
        if 'text' in filetype:
            file = '{}.{}'.format(project.name, 'txt')
        else:
            file = '{}.{}'.format(project.name, filetype.lower())
        if Path(os.path.join(dir, file)).is_file():
            return send_from_directory(dir, file, mimetype=None, as_attachment=True, attachment_filename=file)
    return redirect(url_for('.dashboard'))

app/templates/projects/_projects.html
{% if projects %}
{% for project in projects %}
    {% if project.deleted %}
    {% else %}
	<div class="panel panel-success">
	    <div class="panel-heading">{{ project.name }}</div>
	    <div class="panel-body">
	        <div class="col-sm-7">
		        <p>URL: {{ project.url }}</p>
		        <p>Info: {{ project.requirements }}</p>
		        <p>Id: {{ project.id }}</p>
	        </div>
	        <div class="col-sm-5">
	           {% if project.configured %}
               <div class="dropup">
                    <form action="{{ url_for('projects.delete') }}" method="post">  
                        {{ form.csrf_token }}
                        <input type="hidden" value="{{ project.id }}" name="project_to_delete_id"></input>
                            <button type="submit" value="download" name="download" class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="caret"></span>{{ _('Download') }}</button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                {% if project.download_filetype %}
                                    {% if "CSV" in project.download_filetype %}<li><a href="/projects/download/{{ project.id }}/csv">CSV : {{ project.name }}.csv</a></li>{% endif %}
                                    {% if "Sqlite" in project.download_filetype %}<li><a href="/projects/download/{{ project.id }}/sqlite">Sqlite : {{ project.name }}.sqlite</a></li>{% endif %}
                                    {% if "Text" in project.download_filetype %}<li><a href="/projects/download/{{ project.id }}/text">Text : {{ project.name }}.txt</a></li>{% endif %}
                                {% else %}
                                    <li class="disabled"><a href="#">CSV : {{ project.name }}.csv</a></li>
                                    <li class="disabled"><a href="#">Sqlite : {{ project.name }}.sqlite</a></li>
                                    <li class="disabled"><a href="#">Text : {{ project.name }}.txt</a></li>
                                {% endif %}
                            </ul>
                        <button type="submit" value="update" name="update" class="btn btn-info">{{ _('Update') }}</button>
                        <button type="submit" value="delete" name="delete" class="btn btn-danger">{{ _('Delete') }}</button>    
                    </form>
                </div>
                {% else %}
	                <form action="{{ url_for('projects.delete') }}" method="post">
	                    {{ form.csrf_token }}
	                    <button type="submit" value="download" name="download" class="btn btn-default" disabled>{{ _('Download') }}</button>
	                    <button type="submit" value="update" name="update" class="btn btn-info" disabled>{{ _('Update') }}</button>
	                    <button type="submit" value="delete" name="delete" class="btn btn-danger" disabled>{{ _('Delete') }}</button>
	                </form> 
                {% endif %}
	        </div>
        </div>
    </div>
    {% endif %}
{% endfor %}

{% else %}
   <p>{{ 'No projects have been created yet.' }}
{% endif %}

app/templates/projects/dashboard.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ config['MYPROJ_NAME'] }}  - Dashboard{% endblock %}

{% block page_content %}
<div class="page-header">
        <div class="col-sm-8">
            <h1>Current Projects</h1>            
               {% include 'projects/_projects.html' %}          
        </div>
        <div class="col-sm-4">
            <h1>Create new Project</h1>
            <p>Please fill the form below. We shall get back to you with the quote.</p>
            {{ wtf.quick_form(form) }}
   		</div>

</div>
{% endblock %}

app/templates/projects/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ config['MYPROJ_NAME'] }}{% endblock %}


{% block page_content %}
<div class="page-header">
   <h1>Hello , {% if current_user.is_authenticated %}{{ current_user.username }} and the id of the user is {{ current_user.id }}{% else %}Stranger{% endif %}!</h1>
</div>
{% endblock %}